tanbou-maps/tanbou-maps

README.md
=> docs: README.md に環境開発手順を記載

README.md
`README.md` を編集してローカルの開発用データベースとつなげるための手順を追記しました
=> docs: README.md にデータベース接続のための設定事項を追記

.gitignore
`vite_rails` のための `.gitigore` の追記
=> docs: gitignore の変更

tailwind.config.js
`tailwind.config.js` にコメントを追加しました
=> docs: コメント追加

app/frontend/entrypoints/application.js, app/frontend/stylesheets/style.css, app/frontend/vue/App.vue, tailwind.config.js
Tailwind CSS が適用できるようになったので
`http://127.0.0.1:3000/vue/index` にアクセスするとテストで書いた
"Hello, World!" がTailwind CSS が適用されています
=> chore: Tailwind CSS が適用できるようにコンフィグの設定とテストコードの作成

DEVELOPER.md
=> docs: 開発者用のドキュメントを修正

DEVELOPER.md
`DEVELOPER.md` に
Pull Reqest が承認されたあとの行動規範を追記しました
=> docs: ライブラリの依存関係を直すための記述を追記

app/frontend/entrypoints/application.js, config/routes.rb
`config/routes.rb` の設定がうまくいってなかったため修正
=> fix: routes がうまく設定されていない問題を解決

app/controllers/index_controller.rb, app/frontend/components/Header.vue, app/frontend/components/Index.vue, app/frontend/entrypoints/application.js, app/helpers/index_helper.rb, app/views/index/show.html.erb, config/routes.rb, test/controllers/index_controller_test.rb
`http://127.0.0.1:3000/` のページを作成して簡単に仮実装しました
=> Feature index

app/models/course_spot.rb, app/models/model_course.rb, app/models/model_course_image.rb, db/migrate/20241119020019_create_model_courses.rb, db/migrate/20241119020314_create_course_spots.rb, db/migrate/20241120010415_update_model_courses_table.rb, db/migrate/20241120015752_add_null_constraint_to_public_key_in_model_courses.rb, db/migrate/20241120024957_create_model_course_images.rb, db/schema.rb, test/fixtures/course_spots.yml, test/fixtures/model_course_images.yml, test/fixtures/model_courses.yml, test/models/course_spot_test.rb, test/models/model_course_image_test.rb, test/models/model_course_test.rb
モデルコース機能の実装に向けたスキーマの調整
システムのアナリティクスの有効
モデルコース機能に必要なデータの操作
利用者のデータログの分析, コンテンツの改善
特になし
既存のファイルの動作に影響のある変更はありません
データの整合性のチェック：実行済み
きちんと最新のデータベース状況を反映してください
```
bundle exec rails db:migrate
```
=> feat: モデルコース機能に関わるスキーマの調整

app/frontend/components/SignUp.vue, config/initializers/cors.rb, db/schema.rb
=>  fix: バグの修正

app/controllers/registration_controller.rb, app/frontend/components/SignUp.vue, app/frontend/entrypoints/application.js, app/models/application_user.rb
`http://127.0.0.1:3000/sign-up` にアクセスしたときの Sign Up Page の Layout 作成
=> feat: SignUpPage の Layout 作成

db/migrate/20241124171851_add_application_user_id_to_model_courses.rb, db/migrate/20241125005123_remove_user_id_from_model_courses.rb, db/migrate/20241125005249_remove_name_from_application_users.rb, db/migrate/20241125010444_rename_username_to_nickname_in_application_users.rb, db/schema.rb
application_usersテーブルの
nameカラム → 削除
usernameカラム → nicknameに変更
特になし
name, usernameカラムの利用
⚠ name, usernameカラムを参照している場合は修正してください。⚠
必要に応じてマイグレーションの再構築を行ってください。
```bundle exec rails db:reset```
=> perf: application_usersテーブルのカラムなどに変更を加えました

app/controllers/index_controller.rb, app/controllers/registration_controller.rb, app/views/registration/signup.html.erb, app/views/sessions/signin.html.erb, db/schema.rb
非ログイン状態の際はサインイン画面にリダイレクトされます
`app/views/registration/signin.html.erb` と `app/views/registration/signup.html.erb` の変更
サインイン画面とサインアップ画面は行き来できます
=> サインインとサインアップの機能追加

db/schema.rb
タイムスタンプの形式を修正しました
データベースの構築(マイグレファイルの反映)はこまめに行いましょう。
=> fix: schema.rbの修正

db/schema.rb
`db/schema.rb` の修正
```bash
bundle exec rails db:migrate
```
を実行し schema に整合性ができるようにした
=> fix: schema.rb の修正

app/controllers/model_courses_controller.rb, app/controllers/registration_controller.rb, app/frontend/components/ModelCourseIndex.vue, app/frontend/entrypoints/application.js, app/frontend/packs/application.js, app/helpers/model_courses_helper.rb, app/models/application_user.rb, app/views/model_courses/index.html.erb, app/views/registration/signup.html.erb, config/routes.rb, db/seeds.rb, test/controllers/model_courses_controller_test.rb
旧usernameをnicknameに変更
サインアップ/サインインが正常に動作するようになりました
=> fix: 認証機能の回復

config/routes.rb
routes.rbのバグを修正
正常な処理
必要に応じて環境の再構築をしてください
=> fix: ルートのバグ修正

.github/PULL_REQUEST_TEMPLATE.md, DEVELOPER.md
`DEVELOPER.md` の軽微な修正
今後の PR を書きやすくするために
`.github/PULL_REQUEST_TEMPLATE.md` を作成
=> docs: 開発者用ドキュメントの修正とPRテンプレートを作成

app/controllers/sessions_controller.rb, app/frontend/components/SignIn.vue, app/frontend/components/SignUp.vue, app/models/application_user.rb, app/views/registration/complete.html.erb, app/views/sessions/signin.html.erb, app/views/sessions/signout.html.erb
`127.0.0.1:3000/sign-in`
Sign In 画面を Vue.js を 使ってブラッシュアップ
=> feat: Sign In の画面の作成

DEVELOPER.md
`DEVELOPER.md` に
```bash
git fetch -p
```
の手順を追加しました
=> docs: 開発者用ドキュメントの変更

app/frontend/components/SignIn.vue, app/views/sessions/signin.html.erb
`http://127.0.0.1:3000/sign-in`
Sign In の画面にパスワードの可視化を追加；
<script>部分のコードをブラッシュアップ
=> perf: Sign In の画面の更新

app/frontend/components/SignIn.vue, app/frontend/components/SignUp.vue
`http://127.0.0.1:3000/sign-up`
`http://127.0.0.1:3000/sign-in`
Sign Up と Sign In のvueファイルにコードコメントの追記
=> refactor: Sign In と Sign Up のコードコメントの追記

app/controllers/contacts_controller.rb, app/frontend/components/Contact.vue, app/frontend/components/SignIn.vue, app/frontend/components/SignUp.vue, app/frontend/entrypoints/application.js, app/helpers/contacts_helper.rb, app/models/contact.rb, app/views/contacts/complete.html.erb, app/views/contacts/new.html.erb, config/routes.rb, db/migrate/20241128012852_create_contacts.rb, db/schema.rb, test/controllers/contacts_controller_test.rb, test/fixtures/contacts.yml, test/models/contact_test.rb
`http://127.0.0.1:3000/contacts/new`
Contact の画面が出てくる
=> feat: Contact の画面の作成(一応)

app/frontend/components/Contact.vue, app/views/contacts/terms.html.erb
`127.0.0.1:3000/contacts/terms`
お問い合わせの規約画面をブラッシュアップ
=> perf: お問い合わせの規約の更新

Gemfile, Gemfile.lock, app/controllers/contacts_controller.rb, app/mailers/contact_mailer.rb, app/views/contact_mailer/contact_email.html.erb, app/views/contact_mailer/contact_email.text.erb, config/environments/development.rb, config/environments/production.rb, test/mailers/contact_mailer_test.rb, test/mailers/previews/contact_mailer_preview.rb
`127.0.0.1:3000/contacts/new`
[送信]ボタンを押すと、登録されたGMAILで受け取る可能
=> feat: お問い合わせのメールはGmailを通じて受信可能

app/frontend/components/Index.vue
`127.0.0.1:3000`
[お問い合わせページ]を押すと、お問い合わせのページ（`127.0.0.1:3000/contacts/new`）に遷移する
=> fix: indexより、お問い合わせページへのルートを追加

app/frontend/components/Contact.vue
`127.0.0.1:3000/contacts/new`
[ホームページに戻る]リンクを追加
=> feat: お問い合わせページから、ホームページに戻るリンクを追加

.gitignore, config/environments/development.rb, config/environments/production.rb
`127.0.0.1:3000/contacts/new`
「送信」ボタンを押すと、登録したGMAILに届きました。
=> perf: GMAILの設定の変更

app/frontend/components/SpotPickerComponent.vue, app/frontend/components/SpotShowComponent.vue, app/views/spots/new.html.erb
This pull request includes several changes focused on improving the user interface and user experience in the frontend components and views. The most important changes include updates to the layout and styling of the `SpotPickerComponent`, `SpotShowComponent`, and the form in the `new.html.erb` view for creating new spots.
* [`app/frontend/components/SpotPickerComponent.vue`](diffhunk://#diff-04af575621ee8e7015ccc2c70cac346fd3f10ca18c31b1c100c91e58c12a00b9L2-R19): Simplified the layout by removing unnecessary div wrappers and updated the styling of the search input and map container.
* [`app/frontend/components/SpotShowComponent.vue`](diffhunk://#diff-50e97998c2df660cd0061d7b0663cc54d70377a9aa0fdf437eb11af808712f94L3-R3): Changed the ID of the map element to `spot-show-component` for …
=> Feature style

app/controllers/admin/contents/spots_controller.rb, app/helpers/admin/contents/spots_helper.rb, app/models/categories_spot.rb, app/models/category.rb, app/models/spot.rb, app/models/spot_detail.rb, app/models/spot_tag.rb, app/views/admin/contents/spots/edit.html.erb, app/views/admin/contents/spots/index.html.erb, app/views/admin/contents/spots/new.html.erb, app/views/admin/contents/spots/show.html.erb, config/routes.rb, test/controllers/admin/contents/spots_controller_test.rb
`127.0.0.1:3000/admin/contents/spots`
「新しいスポットを追加する」のリンクをクリックすると、追加できる。
=> feat: 管理者がスポットの情報を追加できる

Gemfile, Gemfile.lock, app/controllers/model_courses_controller.rb, app/frontend/components/App.vue, app/frontend/components/LoadingWave.vue, app/frontend/components/ModelCourseDetail.vue, app/frontend/components/ModelCourseList.vue, app/frontend/entrypoints/application.js, app/frontend/router.js, app/views/model_courses/index.html.erb, package.json, yarn.lock
画面遷移の導線確保
諸動作の改善
Pagination - kaminariの導入
現在時点で他機能への影響は確認できていません。
=> feat: モデルコース画面連携

app/frontend/components/SignOutPage.vue
`127.0.0.1:3000/sign-out`
sign-out完了画面に'ログアウト'から'サインアウト'に変更
=> docs: 'ログアウト'から'サインアウト'に変更

app/controllers/model_courses_controller.rb, app/frontend/components/ModelCourseDetail.vue, app/frontend/components/ModelCourseEdit.vue, app/frontend/components/ModelCourseForm.vue, app/frontend/components/ModelCourseList.vue, app/frontend/components/Review.vue, app/frontend/router.js, app/models/model_course.rb, config/routes.rb, db/migrate/20250130113005_add_details_to_model_courses.rb, db/migrate/20250201103654_add_record_uuid_to_model_courses.rb, db/schema.rb, package-lock.json, package.json, yarn.lock
スポットレビューの評価の初期値を５にセット
これまで：
評価を選択しないで送信するとエラー、最初から入力を求められる
これから：
評価を選択しないで送信した場合、５のままで評価される
=> Hotfix model courses

app/models/spot_detail.rb, app/views/admin/contents/spots/edit.html.erb, app/views/admin/contents/spots/new.html.erb, app/views/admin/contents/spots/show.html.erb
`http://127.0.0.1:3000/admin/contents/spots/new`
`http://127.0.0.1:3000/admin/contents/spots/edit`
`http://127.0.0.1:3000/admin/contents/spots/xx`
スタイルを変更した
=> perf: 管理者機能のパフォーマンスを向上させるコード変更

app/frontend/components/SpotPickerComponent.vue, app/models/spot.rb, app/views/spots/new.html.erb, app/views/spots/show.html.erb
This pull request includes several changes to the `SpotPickerComponent.vue`, `spot.rb`, and related view files to improve functionality and fix minor issues. The most important changes include removing the search functionality from the `SpotPickerComponent.vue`, correcting a typo in the `spot.rb` model, and updating the form fields in the `new.html.erb` and `show.html.erb` views.
Changes to `SpotPickerComponent.vue`:
* Removed the search input field and the `handleSearch` method which handled the search functionality. [[1]](diffhunk://#diff-04af575621ee8e7015ccc2c70cac346fd3f10ca18c31b1c100c91e58c12a00b9L3-L10) [[2]](diffhunk://#diff-04af575621ee8e7015ccc2c70cac346fd3f10ca18c31b1c100c91e58c12a00b9L64-L97)
Minor fixes:
* Corrected a typo in the `Spot` model's `photos` association comment …
=> Hotfix spot

app/frontend/components/ReviewDetail.vue
`http://127.0.0.1:3000/spots/xx/reviews/x`
一番下のリンクは「レビュー閲覧に戻る」に変更
=> style: 「スポット詳細に戻る」から「レビュー閲覧に戻る」に変更

app/frontend/components/Contact.vue
`http://127.0.0.1:3000/contacts/new`
お名前とメッセージには、スペースを入力した場合のエラーメッセージを変更
=> perf: お名前とメッセージには、スペースを入力した場合のエラーメッセージを変更

app/controllers/user_profile_controller.rb, app/views/user_profile/profile_view.html.erb, app/views/user_profile/profile_view_id.html.erb, app/views/user_profile/profileview.html.erb, app/views/user_profile/profileviewid.html.erb, config/routes.rb, test/controllers/vue_controller_test.rb
This pull request includes several changes to the `UserProfileController` and associated views, as well as updates to routes and removal of obsolete test files. The most important changes include renaming methods for consistency, adding JSON data to views, and updating routes accordingly.
* Renamed methods in `UserProfileController` for consistency (`profileview` to `profile_view`, `profileviewid` to `profile_view_id`).
* Added a `show` method to `UserProfileController` to render the current user as JSON.
* Added JSON data and root path to `profile_view.html.erb` and `profile_view_id.html.erb` views. [[1]](diffhunk://#diff-d8827d3b5d60f79743f69bb338dffea2872fa1501dc371ec387eec5e7e8ea3b6R1) [[2]](diffhunk://#diff-5de11c575190e1c4c779d4a776d7b715b21ca8d4e42e23f57c0dc13c48a9134dR1)
* Removed …
=> Feature profile

app/controllers/spots_controller.rb, app/frontend/components/SpotsSearchPage.vue, app/views/spots/index.html.erb, app/views/spots/search.html.erb, config/routes.rb
This pull request includes several significant updates to the spots search functionality, enhancing the user experience and improving code maintainability. The changes include modifications to the controller, frontend component, views, and routes.
* [`app/controllers/spots_controller.rb`](diffhunk://#diff-b567bf8f1409b80250248137a729eab83ff1cbbadd6917a5ad9a5422ab956a62R51-R56): Added functionality to fetch all spots and respond with HTML or JSON format in the `search` action.
* [`app/frontend/components/SpotsSearchPage.vue`](diffhunk://#diff-118ea67815d3959dc8ff8148fd86a478e6a22a751a5fbdc40f1cdc344250fdf2L2-R61): Refactored the component to include a map that dynamically loads spots from the backend and displays them with markers and info windows. Simplified the structure and removed …
=> Feature spot

app/frontend/components/SpotsSearchPage.vue, app/views/spots/search.html.erb
`http://127.0.0.1:3000/spots/search`
スタイルを変更
=> perf: 「スポット一覧を地図で見る」ページのスタイルを変更

app/controllers/model_courses_controller.rb, app/frontend/components/ModelCourseEdit.vue, app/frontend/components/ModelCourseForm.vue
=> Fix model courses

app/controllers/model_courses_controller.rb, app/frontend/components/ModelCourseDetail.vue, app/frontend/components/ModelCourseList.vue, app/frontend/entrypoints/application.js
=> Hotfix model course

app/frontend/components/LoadingScreen.vue, app/frontend/components/ModelCourseDetail.vue, app/frontend/components/ModelCourseList.vue, app/frontend/entrypoints/application.js
消えていたローディングを設定しなおしました
application.jsに変更が加わっていますが多機能に影響はありません。
=> fix:　ローディング再設定

app/controllers/model_courses_controller.rb, app/frontend/components/ModelCourseEdit.vue, app/frontend/entrypoints/application.js, app/views/model_courses/edit.html.erb, config/routes.rb
=> fix: restored editmode

app/views/admin/contents/spots/edit.html.erb, app/views/admin/contents/spots/new.html.erb
`http://127.0.0.1:3000/admin/contents/spots/new`
`http://127.0.0.1:3000/admin/contents/spots/xx/edit`
スポット詳細を表示する部分の修正
=> fix: 管理者機能のバッグの修正

app/views/admin/contents/spots/index.html.erb
`http://127.0.0.1:3000/admin/contents/spots`
「人気スコア」削除
=> pref: admin/contents/spotsのスタイルの変更
